### ISSUE TITLE
Need help to learn more about this tool

### ISSUE THREAD

**Issue by gvenkatsai93** [Sangram2905/NSE_Option_Chain#1]
Hi Sangram,

I recently started with option analysis and found that you have automated process of analyzing the option chain, can you please help me in understanding how the logic exactly works and want is success ratio.

Thanks in advance .

**Comment by Sangram2905** [comment]
Hello,

This program is base on this youtube video 
All the method explain by Nitin sir.
 https://youtu.be/vwSjRO4wGYE

My personal experience is that it's give you the direction 70% time..

Also In my personal experience you can build your own analysis 

I will help you on this program modification as per your logic 

If you need any help email me with your logic 

Sangram.phdake07@gmail.com

Reg,
S
