### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by gurtajs44** [Sangram2905/NSE_Option_Chain#10]
Hi @Sangram2905 ,

I wanted to explore the graph part, But i see this is not running at all. 
Can you let me know what is the issue, I would like to analyze it 
Please let me know whats wrong in the .py file and what are the instructions to run

**Comment by Sangram2905** [comment]
What's the error?? On which graph part.?
Works fine with me.

**Comment by gurtajs44** [comment]
Using [commit](https://github.com/Sangram2905/NSE_Option_Chain/commit/84452064752525f2436540f3b0683df9e879b533 )

It start and I am able to pick the Strike Price for Nifty , but then the window and graph open up and in console I see below error
Post that there is no screen update at all....

**Logs:** 

Main .....
**invalid command name ".!combobox2" 4** --> This seems to be the error 
111 NSE Site data pull error 4  --> This seems to be the error 
First Run
Current Program is running for:  NIFTY

[code.txt](https://github.com/Sangram2905/NSE_Option_Chain/files/10088714/code.txt)

Can you provide the working code version.

**Comment by Sangram2905** [comment]
Hi kindly use  this API
As nse API is not uptodate and definitely not for trading.

You can modify my program of you want 


 https://youtu.be/tghBfHIo2fU
