### ISSUE TITLE
data not updating after time difference is more than 5min

### ISSUE THREAD

**Issue by pknayak82** [Sangram2905/NSE_Option_Chain#6]
data not updating after time difference is more than 5min we need to click ok to update every time

**Comment by Sangram2905** [comment]
Yes, the function is like that only to  give the time difference error from NSE site as you can see NSE index data is stopped at 10:30 AM to 11:00 AM.

if we keep auto update without pressing ok then we never know where the NSE stopped the  data or to may messages as we fetched data every 1 min

**Comment by pknayak82** [comment]
great job done sir

kindly also add strick price adding at begining to  changed automatically as price moving for + -10 stricke above ,below  price 

sample excel attached
https://drive.google.com/file/d/15ofHZ7uEGXRLjI_saDL1BuYML83tuLVb/view?usp=sharing

**Comment by Sangram2905** [comment]
the 10 strike move means 1000 point move in Bank nifty index & 500 Points in Nifty, its happen only 1 or 2 times in 3 month.. & its rare in Trading.. dont spend that much time to code just take direction from Program..
