### ISSUE TITLE
some time data freez no notification need to stop n start pls fix

### ISSUE THREAD

**Issue by pknayak82** [Sangram2905/NSE_Option_Chain#7]
stoped at 14:54 pm

https://drive.google.com/file/d/15GgtXs3Sb4KT1yVuD8ZZdox0q4pFbiQQ/view?usp=sharing

**Comment by Sangram2905** [comment]
Brother, NSE stopped the data....
Plz check NSE data  on official side and Your connection as error 5 is for Network connection

**Comment by Sangram2905** [comment]
Use Updated program
