### ISSUE TITLE
strick price change of oi add twice pls fix

### ISSUE THREAD

**Issue by pknayak82** [Sangram2905/NSE_Option_Chain#8]
https://drive.google.com/file/d/15GgtXs3Sb4KT1yVuD8ZZdox0q4pFbiQQ/view?usp=sharing

https://drive.google.com/file/d/13YQGUbtgD_oslo5KK4kW-kvps4mWG8Zx/view?usp=sharing

**Comment by Sangram2905** [comment]
Yes, I know it's added 2 times but the when we take difference of put to
call CHOI it will cancelled out.

Any how I am modifing  the program for last 6 month and continue to do so.
I know every bit of the program and it's limitations and advantages but it
will never be 100 perfect... As any system in world

You are free to do RnD in program and if you find any breakthrough or some
more analysis then plz share with me. But this type of error notification
is quite annoying.

Hope you understand.

Use Spyder IDE for best performance

**Comment by pknayak82** [comment]
dear sir
thanks for ur great job bug informed was for improvent i have only  liitle bit of knowldge in python and stock.

thanks again   for ur great effort.

**Comment by Sangram2905** [comment]
Bro, you can use following sample line of code in program to Remove the additional index value in calculation, make a copy of program and try for yourself for every call and put side.
Hint on line no (put side) 1443 , 1393 call side.
(Test your python skills, I also learn by my self for Index option trades)

## for put side
 p33 = o2.get((index), 'Change in Open Interest')
 p3_list.append(p33*-1)

**Comment by pknayak82** [comment]
Thanks a lot
