### ISSUE TITLE
Not working on aws and gcp

### ISSUE THREAD

**Issue by buntymehar** [Sangram2905/NSE_Option_Chain#9]
The code is working fine on local pc but not on aws or gcp. Please try yourself. And this is not firewall issue.

**Comment by Sangram2905** [comment]
Hello, I am not expert in AWS or GCP & never used. can't comment about it.

**Comment by Sangram2905** [comment]
Hi, Servers/GCP generally don't even have a display functions and even if they had, may be we wouldn't see it. 

But can you plz run any simple program which include the tkinter that will clear the air, and also try to import python libraries which are use my above program. 

Also if its run them plz share me the idea and basic  knowledge how we can do this, Will share my advance paper trading Bot/Program which is easy to modify with Brokers API  (One step closer to Algo Trading)
